/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import clases.materiales.*;
import clases.cuadros.*;
import conexion.*;
import java.sql.Connection;
import logica.*;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leonardo.ormeno
 */
public class DCustomCraft extends javax.swing.JDialog {
    private Connection conex;
    private Pedidos pedido;
    DefaultTableModel modelo;
    private Liston l1;
    private Vidrio v1;
    private Nordex n1;
    private Varilla va1;
    private double largo;
    private double ancho;
    private String tipoCuadro;
    private double precioCuadro;
    
    static private DVentas dvPadre;
    private DVentas dvP;
    
    private int id_cuadro;
    private int id_liston;
    private int id_frontal;
    private int id_trasera;
    private int id_varilla;
    
    /**
     * Creates new form DCustomCraft
     */
    public DCustomCraft(java.awt.Frame parent, boolean modal,Pedidos p,DVentas dv) {
        super(parent, modal);
        initComponents();
        //INICIALES base de datos
        Conexion cone=new Conexion();
        conex=cone.conectar();
        pedido=p;
        //iniciales
        dvP=dv;
        labelNroPedido.setText(p.getN_pedido());
        llenarListonTabla();
        llenarFrontal();
        llenarTrasera();
        llenarVarilla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bvidrios = new javax.swing.ButtonGroup();
        BtapaTrasera = new javax.swing.ButtonGroup();
        bCotizar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbTipoCuadro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tListon = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfLargo = new javax.swing.JFormattedTextField();
        tfAncho = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbFrontal = new javax.swing.JComboBox<>();
        cbTapaTrasera = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        labelNroPedido = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbVarilla = new javax.swing.JComboBox<>();
        checkVarilla = new javax.swing.JCheckBox();
        checkTrasera = new javax.swing.JCheckBox();
        checkFrontal = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bCotizar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bCotizar.setText("COTIZAR");
        bCotizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCotizarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nro. Pedido:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("TIPO DE CUADRO");

        cbTipoCuadro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLANO", "BOX", "DOBLE MARCO", "DOBLE VIDRIO", "ENMARCADO" }));
        cbTipoCuadro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoCuadroItemStateChanged(evt);
            }
        });
        cbTipoCuadro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoCuadroActionPerformed(evt);
            }
        });

        tListon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESC", "PROF", "MATERIAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tListon);
        if (tListon.getColumnModel().getColumnCount() > 0) {
            tListon.getColumnModel().getColumn(0).setResizable(false);
            tListon.getColumnModel().getColumn(1).setResizable(false);
            tListon.getColumnModel().getColumn(1).setPreferredWidth(280);
            tListon.getColumnModel().getColumn(2).setResizable(false);
            tListon.getColumnModel().getColumn(3).setResizable(false);
            tListon.getColumnModel().getColumn(3).setPreferredWidth(130);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("LISTON:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("COMPLEMENTARIOS:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("TAPA TRASERA:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("TAMAÑO DEL ARTE");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Largo:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Ancho:");

        tfLargo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        tfLargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLargoActionPerformed(evt);
            }
        });

        tfAncho.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        tfAncho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnchoActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfAncho))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("FRONTAL:");

        cbFrontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFrontalActionPerformed(evt);
            }
        });

        cbTapaTrasera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTapaTraseraActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setForeground(new java.awt.Color(255, 102, 102));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("ADICIONALES:");

        jCheckBox2.setText("PASPARTÚ");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("LISTO PARA COLGAR");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox2)
                .addGap(64, 64, 64)
                .addComponent(jCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelNroPedido.setText("000000");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("VARILLA:");

        cbVarilla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Varilla" }));
        cbVarilla.setEnabled(false);
        cbVarilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVarillaActionPerformed(evt);
            }
        });

        checkVarilla.setSelected(true);
        checkVarilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVarillaActionPerformed(evt);
            }
        });

        checkTrasera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTraseraActionPerformed(evt);
            }
        });

        checkFrontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFrontalActionPerformed(evt);
            }
        });

        jLabel12.setText("ON/OFF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbTipoCuadro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbFrontal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(51, 51, 51)
                                                .addComponent(checkFrontal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cbVarilla, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(checkVarilla))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cbTapaTrasera, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(checkTrasera))))
                                        .addGap(15, 15, 15)))
                                .addGap(81, 81, 81))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNroPedido)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bCotizar)
                        .addGap(448, 448, 448))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelNroPedido))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbFrontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkFrontal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkTrasera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(cbTapaTrasera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbTipoCuadro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(cbVarilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkVarilla, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(bCotizar)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void llenarListonTabla(){
        Object[] listonArray=new Object[4];
         modelo = (DefaultTableModel) tListon.getModel();
        try{
                String sSQL="SELECT id,des,prof,mat FROM liston";
                Statement cn=conex.createStatement();
                ResultSet res=cn.executeQuery(sSQL);
                while(res.next()){
                    listonArray[0]=res.getString("id");
                    listonArray[1]=res.getString("des");
                    listonArray[2]=res.getString("prof");
                    listonArray[3]=res.getString("mat");
                    modelo.addRow(listonArray);
                }
            }catch(SQLException e){
                System.out.println(e);
            }  
    }
    public void llenarFrontal(){
        try{
                String sSQL="SELECT des FROM Frontal";
                Statement cn=conex.createStatement();
                ResultSet res=cn.executeQuery(sSQL);
                while(res.next()){
                    cbFrontal.addItem(res.getString("des"));
                }
            }catch(SQLException e){
                System.out.println(e);
            }
    }
    public void llenarTrasera(){
        try{
                String sSQL="SELECT des FROM Trasera";
                Statement cn=conex.createStatement();
                ResultSet res=cn.executeQuery(sSQL);
                while(res.next()){
                    cbTapaTrasera.addItem(res.getString("des"));
                }
            }catch(SQLException e){
                System.out.println(e);
            }
    }
    public void llenarVarilla(){
        try{
                String sSQL="SELECT des FROM varilla";
                Statement cn=conex.createStatement();
                ResultSet res=cn.executeQuery(sSQL);
                while(res.next()){
                    cbVarilla.addItem(res.getString("des"));
                }
            }catch(SQLException e){
                System.out.println(e);
            }
    }
    
    private void bCotizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCotizarActionPerformed
        // TODO add your handling code here:
        largo=Double.parseDouble(tfLargo.getText());
        ancho=Double.parseDouble(tfAncho.getText());
        tipoCuadro=(String) cbTipoCuadro.getSelectedItem();
        id_liston=Integer.parseInt((String) tListon.getValueAt(tListon.getSelectedRow(),0));
        String frontal=null,trasera=null,varilla=null;
        System.out.println(checkFrontal.isSelected());
        System.out.println(checkTrasera.isSelected());
        System.out.println(checkVarilla.isSelected());
        if(checkFrontal.isSelected()==false){
            frontal=(String) cbFrontal.getSelectedItem();
        }
        if(checkTrasera.isSelected()==false){
            trasera=(String) cbTapaTrasera.getSelectedItem();
        }
        if(checkVarilla.isSelected()==false){
            varilla=(String) cbVarilla.getSelectedItem();
        }
        System.out.println("----------EMPIEZA CUADRO CONTROLLER-----------");
        CuadroController cc1=new CuadroController(conex,largo,ancho,tipoCuadro,id_liston,frontal,trasera,varilla);
        cc1.precio_costo_cuadro();
        JOptionPane.showMessageDialog(null,"SE HA COTIZADO CORRECTAMENTE PRECIO COSTO: " + cc1.getPrecioCuadro());
        cc1.grabarCuadro();
        JOptionPane.showMessageDialog(null,"SE HA GRABADO CORRECTAMENTE EL PEDIDO ID: " + cc1.getIdCuadro());
        pedido.crearPedido(pedido.getN_pedido());
        pedido.addCuadro(cc1.getIdCuadro());
        dvP.actualizarTablaCuadros();
        this.dispose();
    }//GEN-LAST:event_bCotizarActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void cbTipoCuadroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoCuadroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoCuadroActionPerformed

    private void cbTapaTraseraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTapaTraseraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTapaTraseraActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void cbVarillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVarillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVarillaActionPerformed

    private void cbTipoCuadroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoCuadroItemStateChanged
        // TODO add your handling code here
        if(cbTipoCuadro.getSelectedIndex()>=1 && cbTipoCuadro.getSelectedIndex()<=3){
            cbVarilla.setEnabled(true);
            checkVarilla.setSelected(false);
        }
        else{
            cbVarilla.setEnabled(false);
            checkVarilla.setSelected(true);
        }
    }//GEN-LAST:event_cbTipoCuadroItemStateChanged

    private void tfAnchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnchoActionPerformed

    private void tfLargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLargoActionPerformed

    private void checkVarillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVarillaActionPerformed
        // TODO add your handling code here:
        cbVarilla.setEnabled(!checkVarilla.isSelected());
    }//GEN-LAST:event_checkVarillaActionPerformed

    private void checkTraseraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTraseraActionPerformed
        // TODO add your handling code here:
        cbTapaTrasera.setEnabled(!checkTrasera.isSelected());
    }//GEN-LAST:event_checkTraseraActionPerformed

    private void cbFrontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFrontalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFrontalActionPerformed

    private void checkFrontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFrontalActionPerformed
        // TODO add your handling code here:
        cbFrontal.setEnabled(!checkFrontal.isSelected());
    }//GEN-LAST:event_checkFrontalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DCustomCraft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DCustomCraft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DCustomCraft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DCustomCraft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Pedidos p1=new Pedidos();
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DCustomCraft dialog = new DCustomCraft(new javax.swing.JFrame(), true,p1,dvPadre);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtapaTrasera;
    private javax.swing.ButtonGroup Bvidrios;
    private javax.swing.JButton bCotizar;
    private javax.swing.JComboBox<String> cbFrontal;
    private javax.swing.JComboBox<String> cbTapaTrasera;
    private javax.swing.JComboBox<String> cbTipoCuadro;
    private javax.swing.JComboBox<String> cbVarilla;
    private javax.swing.JCheckBox checkFrontal;
    private javax.swing.JCheckBox checkTrasera;
    private javax.swing.JCheckBox checkVarilla;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelNroPedido;
    private javax.swing.JTable tListon;
    private javax.swing.JFormattedTextField tfAncho;
    private javax.swing.JFormattedTextField tfLargo;
    // End of variables declaration//GEN-END:variables
}
