/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;
import conexion.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.*;
import alertasVistas.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.sql.Types;
import java.text.DecimalFormat;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
/**
 *
 * @author leonardo.ormeno
 */
public class DVentas extends javax.swing.JDialog {
    private Pedidos pedido;
    DefaultTableModel tmodelo;
    private Connection conex;
    private ArrayList<Integer> idPedido;
    
    /**
     * Creates new form DVentas
     */
    public DVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Conexion cone=new Conexion();
        conex=cone.conectar();
        
        Pedidos p1=new Pedidos();
        pedido=p1;
        String nroPedido=pedido.calcNPedido();
        System.out.println(nroPedido);
        //pedido.crearPedido(nroPedido); -> se pasa a cuando se cotiza un cuadro en DCustomCraft (boton cotizar)
        pedido_label.setText(pedido.getN_pedido());
        tmodelo = (DefaultTableModel) tPedido.getModel();
        //actualizarTablaCuadros();
        
        KeyStroke escapeKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        Action escapeAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose(); // Cerrar el diálogo
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escapeKeyStroke, "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", escapeAction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBuscadorVenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pedido_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPedido = new javax.swing.JTable();
        bBoleta = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bInfoProducto = new javax.swing.JButton();
        bEliminarPedido = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelPrecio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bCantidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("BUSCAR");

        jBuscadorVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscadorVentaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nro de pedido:");

        pedido_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pedido_label.setText("0000101");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cliente:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("No identificado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBuscadorVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pedido_label))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(pedido_label)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel2Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jLabel1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jBuscadorVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripción", "Tamaño Art", "Tipo", "Cant", "Precio U", "Precio T"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tPedido);
        if (tPedido.getColumnModel().getColumnCount() > 0) {
            tPedido.getColumnModel().getColumn(0).setMinWidth(600);
            tPedido.getColumnModel().getColumn(0).setPreferredWidth(600);
            tPedido.getColumnModel().getColumn(0).setMaxWidth(650);
            tPedido.getColumnModel().getColumn(1).setMinWidth(150);
            tPedido.getColumnModel().getColumn(1).setPreferredWidth(150);
            tPedido.getColumnModel().getColumn(1).setMaxWidth(150);
            tPedido.getColumnModel().getColumn(2).setResizable(false);
            tPedido.getColumnModel().getColumn(2).setPreferredWidth(60);
            tPedido.getColumnModel().getColumn(3).setResizable(false);
            tPedido.getColumnModel().getColumn(3).setPreferredWidth(1);
            tPedido.getColumnModel().getColumn(4).setResizable(false);
            tPedido.getColumnModel().getColumn(4).setPreferredWidth(2);
            tPedido.getColumnModel().getColumn(5).setResizable(false);
            tPedido.getColumnModel().getColumn(5).setPreferredWidth(2);
        }

        bBoleta.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        bBoleta.setText("BOLETA");
        bBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBoletaActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton3.setText("FACTURA");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setIconTextGap(10);
        jButton3.setMargin(new java.awt.Insets(2, 0, 3, 0));
        jButton3.setRolloverEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        bInfoProducto.setText("Info Producto");
        bInfoProducto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bInfoProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bInfoProducto.setInheritsPopupMenu(true);
        bInfoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInfoProductoActionPerformed(evt);
            }
        });

        bEliminarPedido.setText("Eliminar Producto");
        bEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarPedidoActionPerformed(evt);
            }
        });

        labelPrecio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        labelPrecio.setText("99.99");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("S/");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPrecio)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecio)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        bCantidad.setText("Cambiar Cant");
        bCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCantidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(326, 326, 326)
                                .addComponent(bInfoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(bEliminarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(bCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bEliminarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bInfoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void limpiarTablaCuadros(){        
        tmodelo.setRowCount(0);
    }
    
    public void actualizarTablaCuadros(){
        //tPedido.setVisible(false);
        System.out.println("ESTO ES UN EVENTO DISPARADO POS DCUSTOMVENTA ASOCIADO AL PEDIDO NRO:"+pedido.getN_pedido());
        System.out.println("Inicio de la Limpieza de la tabla");
        limpiarTablaCuadros();
        System.out.println("Fin de la limpieza de la tabla");
        try {
            System.out.println("rellenar tabla");
            String sSQL = "SELECT vd.id_vta_det,c.des, c.tipo, c.precio, c.tam, vd.cant,vd.pedido_precio FROM pedido p JOIN vta_det vd ON p.id_pedido = vd.pedido JOIN cuadro c ON vd.cuadro = c.id_cuadro WHERE p.N_PEDIDO = '"+pedido.getN_pedido()+"' AND vd.est_ped='S';";
            Statement cn = conex.createStatement();
            ResultSet res = cn.executeQuery(sSQL);
            ArrayList<Integer> idP = new ArrayList<>();
            while (res.next()) {
                // Crear un ArrayList para almacenar los datos de la fila
                ArrayList<Object> fila = new ArrayList<>();
                idP.add(res.getInt("id_vta_det"));
                fila.add(res.getString("des"));
                fila.add(res.getString("tam"));
                fila.add(res.getString("tipo"));
                fila.add((Object) res.getDouble("cant"));
                fila.add((Object) res.getDouble("precio"));
                fila.add((Object) res.getDouble("pedido_precio"));
                // Agregar la fila al modelo de tabla
                tmodelo.addRow(fila.toArray());
                idPedido=idP;
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        precioActualizar();
        //tPedido.setVisible(true);
    }
    
    private void bEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarPedidoActionPerformed
        // TODO add your handling code here:
        int id=-1;
        try{
            id=idPedido.get(tPedido.getSelectedRow());
            try{
            String procedimiento="{ CALL vta_det_pedido_estado(?) }";
                try (CallableStatement cs = conex.prepareCall(procedimiento)) {
                    // Establecer el parámetro del procedimiento
                    cs.setInt(1, id);

                    // Ejecutar el procedimiento
                    ResultSet rs = cs.executeQuery();
                    JOptionPane.showMessageDialog(null, "SE ELIMINO EL PEDIDO");
                }
            }catch (SQLException e) {
                System.out.println(e);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "SELECIONE UN CUADRO");
        }
        actualizarTablaCuadros();
    }//GEN-LAST:event_bEliminarPedidoActionPerformed

    private void bInfoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInfoProductoActionPerformed
        // TODO add your handling code here:
        int id=-1;
        try{
            id=idPedido.get(tPedido.getSelectedRow());
            try{
            String procedimiento="{ CALL pedido_cuadro_detalles(?) }";
                try (CallableStatement cs = conex.prepareCall(procedimiento)) {
                    // Establecer el parámetro del procedimiento
                    cs.setInt(1, id);

                    // Ejecutar el procedimiento
                    ResultSet rs = cs.executeQuery();

                    // Procesar los resultados
                    while (rs.next()) {
                        // Aquí puedes procesar los resultados como desees
                        // Por ejemplo, imprimir los valores en la consola
                        System.out.println("Largo: " + rs.getDouble("largo"));
                        System.out.println("Ancho: " + rs.getDouble("ancho"));
                        System.out.println("Tipo: " + rs.getString("tipo"));
                        System.out.println("Liston: " + rs.getString("ldes"));
                        System.out.println("Frontal: " + rs.getString("fdes"));
                        System.out.println("Tapa: " + rs.getString("tdes"));
                        System.out.println("Varilla: " + rs.getString("vnombre"));
                        JOptionPane.showMessageDialog(
                        this, 
                        "<html><body><p style='width: 200px;'>"+"Largo: " + rs.getDouble("largo")+" CM</p>"
                                + "<p style='width: 200px;'>"+"Ancho: " + rs.getDouble("ancho")+" CM</p>"
                                        + "<p style='width: 200px;'>"+"Tipo: " + rs.getString("tipo")+"</p>"
                                                + "<p style='width: 200px;'>"+"Liston: " + rs.getString("ldes")+"</p>"
                                                        + "<p style='width: 200px;'>"+"Frontal: " + rs.getString("fdes")+"</p>"
                                                                + "<p style='width: 200px;'>"+"Tapa: " + rs.getString("tdes")+"</p>"
                                                                        + "<p style='width: 200px;'>"+"Varilla: " + rs.getString("vnombre")+"</p>"
                                        + "</body></html>", 
                        "DETALLE DEL CUADRO", 
                        JOptionPane.PLAIN_MESSAGE);
                        // Y así sucesivamente para cada columna devuelta por el procedimiento
                    }
                }
            }catch (SQLException e) {
                System.out.println(e);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "SELECIONE UN CUADRO");
        }
       
    }//GEN-LAST:event_bInfoProductoActionPerformed
    public void precioActualizar() {
        float precio = 0;
        int id=pedido.getIdPedido();
        try {
            String procedimiento = "{ CALL vta_det_calc_total(?, ?) }";
            try (CallableStatement cs = conex.prepareCall(procedimiento)) {
                // Establecer el parámetro de entrada del procedimiento
                cs.setInt(1,id);
                // Registrar el parámetro de salida del procedimiento
                cs.registerOutParameter(2, Types.FLOAT);
                // Ejecutar el procedimiento
                cs.execute();
                // Obtener el valor del parámetro de salida
                precio = cs.getFloat(2);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        labelPrecio.setText(String.valueOf(precio));
    }
    
    public boolean verificadorDeVenta(){
        boolean verificador=false;
        try{
            String sSQL="{ CALL verificar_vta_cab(?, ?) }";
            try (CallableStatement cs = conex.prepareCall(sSQL)){
                // Establecer el parámetro de entrada del procedimiento
                cs.setInt(1,pedido.getIdPedido());
                // Registrar el parámetro de salida del procedimiento
                cs.registerOutParameter(2, Types.BOOLEAN);
                // Ejecutar el procedimiento
                cs.execute();
                // Obtener el valor del parámetro de salida
                verificador = cs.getBoolean(2);
                System.out.println("se finalizo la venta? : "+verificador);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e, "ERROR AL REVISAR SI SE HIZO LA VENTA", JOptionPane.ERROR_MESSAGE);
        }
        return verificador;
    }
    
    private void bBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBoletaActionPerformed
        // TODO add your handling code here:
        ClienteVista clientevista = new ClienteVista(new javax.swing.JFrame(), true);
        clientevista.setLocationRelativeTo(this);
        clientevista.setVisible(true);
        String name = clientevista.nameCliente;
        CobroVista cv1 = new CobroVista(new javax.swing.JFrame(), true, pedido.getIdPedido(), name);
        cv1.setLocationRelativeTo(this);
        cv1.setVisible(true);
        do {
            jLabel5.setText(name);
            if (verificadorDeVenta()) {
                reiniciar();
                break;
            }
        } while (verificadorDeVenta()==true);
        System.out.println("fueraaaaaaa");
    }//GEN-LAST:event_bBoletaActionPerformed
    
    private void jBuscadorVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscadorVentaActionPerformed
        // TODO add your handling code here:
        /*
        DMedidas dmedidas=new DMedidas(new javax.swing.JFrame(),true);
        dmedidas.setLocationRelativeTo(this);
        dmedidas.setVisible(true);*/
        DCustomCraft dcustom=new DCustomCraft(new javax.swing.JFrame(), true,pedido,this);
        dcustom.setLocationRelativeTo(this);
        dcustom.setVisible(true);
    }//GEN-LAST:event_jBuscadorVentaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    
  
    
    private void bCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCantidadActionPerformed
        // TODO add your handling code here:
        try{
            int id=idPedido.get(tPedido.getSelectedRow());
            CantidadPedido cant_ped=new CantidadPedido(new javax.swing.JFrame(), true,id);
            cant_ped.setLocationRelativeTo(this);
            cant_ped.setVisible(true);
            if(cant_ped.getCantidad()>0){
                pedido.cambiarCant(id, cant_ped.getCantidad());
            }else{
                JOptionPane.showMessageDialog(null, "SELECIONE UNA CANTIDAD VALIDA");
            }
            actualizarTablaCuadros();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "SELECIONE UN CUADRO");
        }
    }//GEN-LAST:event_bCantidadActionPerformed

    private void reiniciar(){
        // Cerrar el diálogo
        dispose();
        // Cerrar la ventana principal si aún está abierta
        if (this != null) {
            this.dispose();
        }
        // Crear una nueva instancia de la ventana principal y mostrarla
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                DVentas dialog = new DVentas(new javax.swing.JFrame(), true);
                dialog.setLocation(getLocation());
                dialog.setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DVentas dialog = new DVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBoleta;
    private javax.swing.JButton bCantidad;
    private javax.swing.JButton bEliminarPedido;
    private javax.swing.JButton bInfoProducto;
    private javax.swing.JTextField jBuscadorVenta;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel pedido_label;
    private javax.swing.JTable tPedido;
    // End of variables declaration//GEN-END:variables
}
