/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package alertasVistas;

import clases.materiales.Adicional;
import conexion.Conexion;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leonardo.ormeno
 */
public class AdicionalAdd extends javax.swing.JDialog {
    DefaultTableModel tmodelo;
    protected int idAdi;
    private Connection conex;
    protected Adicional adi;
    /**
     * Creates new form AdicionalAdd
     */
    public AdicionalAdd(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Conexion cone=new Conexion();
        conex=cone.conectar();
        tmodelo = (DefaultTableModel) tAdicional.getModel();
        actualizarTablaAdicional();
    }

    public void setIdAdi(int idAdi) {
        this.idAdi = idAdi;
    }

    public void setAdi(Adicional adi) {
        this.adi = adi;
    }

    public Adicional getAdi() {
        return adi;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tAdicional = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tAdicional.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descripción", "Categoría", "Métrica", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tAdicional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tAdicionalKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tAdicional);
        if (tAdicional.getColumnModel().getColumnCount() > 0) {
            tAdicional.getColumnModel().getColumn(0).setResizable(false);
            tAdicional.getColumnModel().getColumn(0).setPreferredWidth(30);
            tAdicional.getColumnModel().getColumn(1).setResizable(false);
            tAdicional.getColumnModel().getColumn(1).setPreferredWidth(200);
            tAdicional.getColumnModel().getColumn(2).setResizable(false);
            tAdicional.getColumnModel().getColumn(3).setResizable(false);
            tAdicional.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("SELECIONE Y DE ENTER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void tAdicionalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tAdicionalKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tAdicional.getSelectedRow() != -1) {
                Object valor = tAdicional.getValueAt(tAdicional.getSelectedRow(), 0);
                System.out.println("Valor de la primera columna seleccionada: " + valor);
                int id=Integer.parseInt(valor.toString());
                CantidadAdicional cant_add=new CantidadAdicional(new javax.swing.JFrame(), true);
                cant_add.setLocationRelativeTo(this);
                cant_add.setVisible(true);
                setAdi(getAdicional(id,cant_add.getCant()));
                setIdAdi(id);
                this.dispose();
            } else {
                System.out.println("No hay fila seleccionada");
            }
        }
    }//GEN-LAST:event_tAdicionalKeyPressed
    
    public Adicional getAdicional(int id, int cant){
        try{
            String sSQL="SELECT * FROM adicional WHERE id_adicional="+id;
            Statement cn=conex.createStatement();
            ResultSet res=cn.executeQuery(sSQL);
            while(res.next()){
                Adicional a=new Adicional(
                id,
                res.getString("des"),
                res.getString("des_corta"),
                res.getString("categoria"),
                res.getString("tipo_metrica"),
                res.getDouble("precio_costo_unidad"),
                res.getInt("cant_paquete"),
                res.getFloat("precio_venta_total"),
                cant
                );
                System.out.println("Se selecciono el adicional: "+a.getDes_corta()+" cant:"+a.getCant());
                return a;
            }
        }catch(SQLException e){
            System.out.println(e);
        }
        System.out.println("ERROR AL OBTENER ADICIONAL!!!");
        return null;
    }
    
    //Mostrar tabla de adicional
    public void limpiarTablaCuadros(){        
        tmodelo.setRowCount(0);
    }
    public void actualizarTablaAdicional(){
        System.out.println("Inicio de la Limpieza de la tabla");
        limpiarTablaCuadros();
        System.out.println("Fin de la limpieza de la tabla");
        try {
            System.out.println("rellenar tabla");
            String sSQL = "SELECT id_adicional,des,categoria,tipo_metrica,precio_venta_total FROM adicional;";
            Statement cn = conex.createStatement();
            ResultSet res = cn.executeQuery(sSQL);
            //ArrayList<Integer> idP = new ArrayList<>();
            while (res.next()) {
                // Crear un ArrayList para almacenar los datos de la fila
                ArrayList<Object> fila = new ArrayList<>();
                fila.add(res.getString("id_adicional"));
                fila.add(res.getString("des"));
                fila.add(res.getString("categoria"));
                fila.add(res.getString("tipo_metrica"));
                fila.add(res.getString("precio_venta_total"));
                // Agregar la fila al modelo de tabla
                tmodelo.addRow(fila.toArray());
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionalAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionalAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionalAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionalAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdicionalAdd dialog = new AdicionalAdd(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tAdicional;
    // End of variables declaration//GEN-END:variables
}
